const Firebird = require("node-firebird");
require("dotenv").config();

const options = {
    host: process.env.FIREBIRD_HOST,
    port: process.env.FIREBIRD_PORT,
    database: process.env.FIREBIRD_DATABASE,
    user: process.env.FIREBIRD_USER,
    password: process.env.FIREBIRD_PASSWORD,
    lowercase_keys: false,
    role: null,
    pageSize: 4096,
    WireCrypt: process.env.FIREBIRD_WIRECRYPT,
};

const pool = Firebird.pool(5, options);

function queryDatabase(sql, params = []) {
    return new Promise((resolve, reject) => {
        pool.get((err, db) => {
            if (err) {
                console.error("Firebird Connection Error:", err);
                return reject(err);
            }

            db.query(sql, params, (err, result) => {
                if (err) {
                    console.error("❌ Query Error:", err);
                    db.detach();
                    pool.destroy();
                    return reject(err);
                }

                if (sql.toLowerCase().startsWith('update') || sql.toLowerCase().startsWith('delete')) {
                    console.log(`Query successful`);
                    db.detach();
                    pool.destroy();
                    return resolve({ rowsAffected: result });
                }

                if (result && Array.isArray(result)) {
                    const formattedResult = result.map(row => {
                        return Object.fromEntries(
                            Object.entries(row).map(([key, value]) => [key.toLowerCase(), value])
                        );
                    });

                    console.log("Query Result:", formattedResult);
                    db.detach();
                    pool.destroy();
                    resolve(formattedResult);
                } else {
                    console.log("Query executed successfully but no data returned.");
                    db.detach();
                    pool.destroy();
                    resolve(result);
                }
            });
        });
    });
}

// queryDatabase(`
//     CREATE TABLE forms (
//         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//         user_id INT NOT NULL,
//         form_type VARCHAR(255) NOT NULL,
//         start_date VARCHAR(255) NOT NULL,
//         end_date VARCHAR(255) NOT NULL,
//         reason VARCHAR(255),
//         status INT NOT NULL,
//         image_original BLOB,
//         image_processed BLOB,
//         FOREIGN KEY (user_id) REFERENCES users(id)
//     );`);

// queryDatabase("select * from forms;")

module.exports = queryDatabase;
