name: Run React Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: test  # Linting runs after tests
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: ./frontend  # Specify the frontend folder

      - name: Run ESLint (frontend)
        run: npm run lint
        working-directory: ./frontend  # Specify the frontend folder